version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - frontend
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c"
    command: >
      "trap exit TERM;
       while :; do
         certbot renew --webroot -w /var/www/certbot &&
         nginx -s reload;
         sleep 12h;
       done"
    restart: unless-stopped

  frontend:
    image: node:18
    container_name: frontend
    working_dir: /app
    volumes:
      - ./client:/app
    command: sh -c "npm install && npm run build"
